### ISSUE TITLE
Unable to parse argument type: minecraft:player

### ISSUE THREAD

**Issue by NurFabi** [lucko/commodore#33]
Hello,

I would like to use commodore and commodore files with my plugin, but when I start the server and the plugin is loaded, I get the following error: **`Unable to parse argument type: minecraft:player (at line 2)`**.

I use as server software Paper 1.19.3 with the 1.19.4 comes the same error.

**Comment by CyberedCake** [comment]
Commodore does not have a minecraft:player namespace for when it checks your file. You should instead use a brigadier:string in the file and return a list of online players' usernames in your plugin. 

I do wonder if it's possible to get the "@a" selector like in vanilla Minecraft, but I'm not sure. I was thinking that was possibly what you were asking here, as maybe a feature request? Otherwise, you'll just have to use the solution I mentioned above.
